SELECT 
    BARANG.KODEBRG, 
    BARANG.NAMABRG, 
    COALESCE(SUM(JUAL.JUMLAH), 0) AS JML_JUAL
FROM 
    BARANG
LEFT JOIN 
    JUAL ON BARANG.KODEBRG = JUAL.KODEBRG
GROUP BY 
    BARANG.KODEBRG, BARANG.NAMABRG;